export const partners = [
    {path: "/images/partners/5-PhotoRoom.png"},
    {path: "/images/partners/archFishComp.png"},
    {path: "/images/partners/archVodokanal.png"},
    {path: "/images/partners/artego.png"},
    {path: "/images/partners/CSP.png"},
    {path: "/images/partners/GAZ.png"},
    {path: "/images/partners/interprom.png"},
    {path: "/images/partners/MosPivZavod.png"},
    {path: "/images/partners/mytisch.png"},
    {path: "/images/partners/ODKSaturn.png"},
    {path: "/images/partners/petroproject.png"},
    {path: "/images/partners/saturn.png"},
    {path: "/images/partners/specAuto.png"},
    {path: "/images/partners/Stroy.png"},
    {path: "/images/partners/teremok.png"},
    {path: "/images/partners/ULK.png"},
    {path: "/images/partners/unirBau.png"},
    {path: "/images/partners/vologdaIce.png"},
]
